spring:
  application:
    name: demo-app
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  main:
    allow-circular-references: true
  datasource:
    druid:
      initial-size: 1
      min-idle: 5
      max-active: 200
      log-abandoned: true
      remove-abandoned: true
      remove-abandoned-timeout: 180
      max-wait: 2000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-perConnection-size: 20
      filters: stat
  cloud:
    sentinel:
      datasource:
        r1:
          nacos:
            data-id: ${spring.application.name}-sentinel-flow
            data-type: json
            rule-type: flow
        r2:
          nacos:
            data-id: ${spring.application.name}-sentinel-degrade
            data-type: json
            rule-type: degrade
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml,classpath:/mybatis/ext-mapper/*.xml
dubbo:
  registry:
    protocol: spring-cloud
    default: false
    address: localhost
  cloud:
    subscribed-services:
  registries:
    nacos:
      default: true

xxl:
  job:
    accessToken: default_token
    executor:
      appname: ${spring.application.name}
      address:
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

