spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/archetype_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

server:
  port: 8092
dubbo:
  protocol:
    port: 20899
  provider:
    telnet: ls,ps,cd,pwd,trace,count,invoke,select,status,log,help,clear,exit,shutdown

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
