spring:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/archetype_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

