spring:
  redis:
    host: host
    port: 6379
    password: password
    database: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_name?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: username
    password: password
server:
  port: 8092
dubbo:
  protocol:
    port: 20889
